# Target specific macros
TARGET = i2cBlinkTest
TARGET_SOURCES := \
	AdcIF.c \
	i2cBlinkTest.c 
	
TOPPERS_OSEK_OIL_SOURCE := ./i2cBlinkTest.oil

O_PATH ?= build

include ../../../../../nxtOSEK/ecrobot/ecrobot.mak
