TARGET = masterBrick1
TARGET_SOURCES := master.c \
					bsw/ADC/AdcIF.c \
					bsw/DIO/DioIF.c 
TOPPERS_OSEK_OIL_SOURCE := ./master.oil
O_PATH ?= build
include ../../../../../../../nxtOSEK/ecrobot/ecrobot.mak 