<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="autosarMetaModel" nsURI="http://www.example.org/autosarMetaModel"
    nsPrefix="autosarMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="BaseClass" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerClientPort" eSuperTypes="#//SoftwarePort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ServerClientPortType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SWC" eSuperTypes="#//BaseClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runnable" upperBound="-1"
        eType="#//Runnable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//Port"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerPort" eSuperTypes="#//SoftwarePort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TriggerPortType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SenderReceiverPort" eSuperTypes="#//SoftwarePort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SenderReceiverPortType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Runnable" eSuperTypes="#//BaseClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//BaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationManager" eSuperTypes="#//BaseClass #//Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bt_address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationMode" lowerBound="1"
        eType="#//OperationMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//SoftwarePort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//SoftwarePort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Motor" eSuperTypes="#//ECUPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="Taster" eSuperTypes="#//ECUPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ultraschall" eSuperTypes="#//ECUPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//BaseClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="swc" upperBound="-1" eType="#//SWC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brick" upperBound="-1"
        eType="#//Brick" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationMode">
    <eLiterals name="MASTER"/>
    <eLiterals name="SLAVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorSensor" abstract="true" eSuperTypes="#//BaseClass #//Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNr" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="I2CExpander" eSuperTypes="#//ActuatorSensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="#//IC2Mode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADC" eSuperTypes="#//ActuatorSensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="LEDPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Brick">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareconnection" upperBound="-1"
        eType="#//HardwareConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerPortType">
    <eLiterals name="INPUT"/>
    <eLiterals name="OUTPUT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServerClientPortType">
    <eLiterals name="SERVER"/>
    <eLiterals name="CLIENT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SenderReceiverPortType">
    <eLiterals name="SENDER"/>
    <eLiterals name="RECEIVER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECUPort" abstract="true" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwarePort" abstract="true" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareport" lowerBound="1"
        eType="#//ECUPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IC2Mode">
    <eLiterals name="DIO"/>
    <eLiterals name="ADC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DIO" eSuperTypes="#//ActuatorSensor"/>
</ecore:EPackage>
